#!/usr/bin/php
<?php

include __DIR__ . '/../init.php';
include __DIR__ . '/../pdo_connect.php';
include __DIR__ . '/../config.php';

echo "Configuration file loaded\n";

$pdo = DBConnector::getPDO();

echo "Application path: " . APPLICATION_PATH ."\n";

$prefix = empty($argv[1])
	? 'resyst'
	: $argv[1];

$createMain = "
	CREATE TABLE IF NOT EXISTS `{$prefix}_db` (
  	  `id` int(11) NOT NULL AUTO_INCREMENT,
  	  `time` datetime NOT NULL,
  	  `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  	  `text` text CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  	  `tag` int(11) NOT NULL,
  	  PRIMARY KEY (`id`)
	) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
";

$createTag = "
	CREATE TABLE IF NOT EXISTS `{$prefix}_tag` (
  	  `id` int(11) NOT NULL AUTO_INCREMENT,
  	  `tagname` varchar(32) COLLATE utf8_czech_ci NOT NULL,
  	  `parenttag` varchar(32) COLLATE utf8_czech_ci NOT NULL,
  	  `colour` varchar(6) COLLATE utf8_czech_ci NOT NULL,
  	  PRIMARY KEY (`id`)
	) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
";

$createUser = "
	CREATE TABLE IF NOT EXISTS `{$prefix}_user` (
  	  `id` int(11) NOT NULL AUTO_INCREMENT,
  	  `login` varchar(16) COLLATE utf8_czech_ci NOT NULL,
  	  `password` varchar(256) COLLATE utf8_czech_ci NOT NULL,
  	  `active` tinyint(1) NOT NULL DEFAULT '1',
  	  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	  `display_name` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
  	  PRIMARY KEY (`id`),
  	  UNIQUE KEY `login` (`login`)
	) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
";

$insertTag = "
	INSERT INTO `{$prefix}_tag` (`id`, `tagname`, `parenttag`, `colour`)
	VALUES
		(1, 'projects', '', 'ffff00'),
		(2, 'general', '', 'ff0000'),
		(3, 'hw', 'projects', 'ff00ff'),
		(4, 'l1', '', '7f7f00'),
		(5, 'l2', 'l1', 'ff005f'),
		(6, 'l3', 'l2', 'ff5f00'),
		(7, 'l4', 'l3', '5fff00'),
		(8, 'under L1', 'l1', '00bbbb'),
		(9, 'new tag', 'under L1', '6c98dd'),
		(10, 'poems', '', '8ed1b');
";

$insertMain = "
	INSERT INTO `{$prefix}_db` (`id`, `time`, `name`, `text`, `tag`)
	VALUES
		(1, '2015-05-08 19:56:36', 'article1', '111111111111<br />111111111111111', 1),
		(2, '2015-05-12 19:56:36', 'article2', '222222222222222<br />ggggggggggggg', 2),
		(3, '2015-05-13 19:56:36', 'article3', 'test words', 3),
		(4, '2015-05-15 19:56:36', 'article4', 'more test words', 4),
		(5, '2015-05-17 19:56:36', 'article5', 'another test words', 5),
		(6, '2015-05-18 19:56:36', 'article6', 'even more test words', 6),
		(7, '2015-05-21 19:56:36', 'article7', 'i do not know what to write here', 7),
		(8, '2015-05-22 19:56:36', 'article8', 'it is not even better now', 8),
		(9, '2015-05-24 19:56:36', 'article9', 'oh damn, why there are so many testing articles', 9),
		(10, '2015-05-26 19:56:36','article10', 'heck yeah, the last one', 10)
";

$insertUser = "
	INSERT INTO `{$prefix}_user` (`id`, `login`, `password`, `active`, `created_at`, `display_name`)
	VALUES
		(1, 'admin', '9dd4e461268c8034f5c8564e155c67a6', 1, '2015-05-26 19:56:36', 'helvetor');
";

$order = array(
	'createMain',
	'createTag',
	'createUser',
	'insertTag',
	'insertMain',
	'insertUser',
);

foreach ($order as $i => $command) {
	$pdo->query($$command);
	echo "Command $command executed. "
		. (count($order) - 1 - $i) . " commands left...\n";
}

echo "Build complete.\n";
